name: flutter_riverpod_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1000001
# 版本: 1.0.0
# 版本号: 1000001
# 版本号格式: 1 00 00 01
# 版本号格式: 主版本号.次版本号.修订号.构建号

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # ===== 基础 UI 组件 =====
  # 许可: MIT - 用途: iOS 风格图标
  cupertino_icons: ^1.0.8
  # 许可: MIT - 用途: 屏幕适配工具
  flutter_screenutil: ^5.9.3
  # 许可: MIT - 用途: 轻量级提示和弹窗
  bot_toast: ^4.1.3

  # ===== 架构核心 =====
  # 许可: MIT - 用途: 状态管理解决方案
  flutter_riverpod: ^2.6.1
  # 许可: BSD - 用途: 应用程序路由导航
  go_router: ^15.1.2

  # ===== 网络和连接 =====
  # 许可: MIT - 用途: HTTP 客户端
  dio: ^5.8.0+1
  # 许可: MIT - 用途: 网络连接状态检测
  connectivity_plus: ^6.1.4
  # 许可: MIT - 用途: 缓存管理
  flutter_cache_manager: ^3.4.1

  # ===== 本地存储 =====
  # 许可: BSD - 用途: 本地键值对存储
  shared_preferences: ^2.5.3
  # 许可: BSD - 用途: 安全存储敏感数据
  flutter_secure_storage: ^9.2.4

  # ===== 设备信息和权限 =====
  # 许可: BSD - 用途: 获取应用包信息
  package_info_plus: ^8.3.0
  # 许可: BSD - 用途: 获取设备信息
  device_info_plus: ^11.3.0
  # 许可: MIT - 用途: 设备标识符获取
  mobile_device_identifier: ^0.0.3
  # 许可: MIT - 用途: 权限处理
  permission_handler: ^12.0.0+1
  # 许可: MIT - 用途: 应用跟踪透明度请求
  app_tracking_transparency: ^2.0.6+1

  # ===== 第三方登录认证 =====
  # 许可: Apache - 用途: 苹果登录
  sign_in_with_apple: ^7.0.1
  # 许可: BSD - 用途: 谷歌登录
  google_sign_in: ^6.2.2

  # ===== 支付和应用内购买 =====
  # 许可: BSD - 用途: 应用内购买核心
  in_app_purchase: ^3.2.3
  # 许可: BSD - 用途: Android 应用内购买
  in_app_purchase_android: ^0.4.0
  # 许可: BSD - 用途: iOS 应用内购买
  in_app_purchase_storekit: ^0.4.0

  # ===== 系统交互和分享 =====
  # 许可: BSD - 用途: 启动URL（网页、电话等）
  url_launcher: ^6.3.1
  # 许可: Apache - 用途: 分享内容到其他应用
  share_plus: ^11.0.0

  # ===== 工具和实用类 =====
  # 许可: BSD - 用途: 国际化和本地化
  intl: ^0.20.2
  # 许可: BSD - 用途: 日志记录
  logger: ^2.5.0
  # 许可: MIT - 用途: 生成唯一标识符
  uuid: ^4.5.1
  # 许可: BSD - 用途: 加密算法库
  crypto: ^3.0.6
  # 许可: BSD - 用途: MIME 类型检测和处理
  mime: ^2.0.0

  # ===== 开发和构建工具 =====
  # 许可: MIT - 用途: 应用图标生成
  flutter_launcher_icons: ^0.14.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/image/global/
    - assets/image/splash/

